CREATE DATABASE LaptopData;


USE LaptopData;
CREATE TABLE laptops (
    id INT AUTO_INCREMENT PRIMARY KEY,
    image_url VARCHAR(255),
    laptop_name VARCHAR(255),
    score VARCHAR(255),
    price varchar(255),
    brand VARCHAR(255),
    model VARCHAR(255),
    colors VARCHAR(255),
    dimensions VARCHAR(255),
    thickness VARCHAR(255),
    weight VARCHAR(255),
	operating_system VARCHAR(255),
    operating_system_type VARCHAR(255),
    ssd_capacity VARCHAR(255),
    ram VARCHAR(255),
    ram_type VARCHAR(255),
    memory_slots VARCHAR(255),
    expandable_memory VARCHAR(255),
    memory_layout VARCHAR(255),
    capacity VARCHAR(255),
    processor VARCHAR(255),
    graphic_processor VARCHAR(255),
    clockspeed VARCHAR(255),
    battery_type VARCHAR(255),
    battery_cell VARCHAR(255),
    power_supply VARCHAR(255),
    display_touchscreen VARCHAR(255),
    pixel_density VARCHAR(255),
    display_size VARCHAR(255),
    display_features VARCHAR(255),
    display_resolution VARCHAR(255),
    display_type VARCHAR(255),
    sound_technologies VARCHAR(255),
    video_recording VARCHAR(255),
    speakers VARCHAR(255),
    microphone_type VARCHAR(255),
    webcam VARCHAR(255),
    inbuilt_microphone VARCHAR(255),
    wireless_lan VARCHAR(255),
    bluetooth_version VARCHAR(255),
    bluetooth VARCHAR(255),
    sales_package VARCHAR(255),
    warranty VARCHAR(255),
    fingerprint_scanner VARCHAR(255),
    keyboard VARCHAR(255),
    headphone_jack VARCHAR(255),
    microphone_jack VARCHAR(255)
);

select * from laptops;


CREATE TABLE mobiles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    image_url VARCHAR(255),
    mobile_name VARCHAR(255),
    score VARCHAR(25),
    price varchar(255),
    display VARCHAR(255),
    rear_camera VARCHAR(255),
    front_camera VARCHAR(255),
    battery VARCHAR(255),
    processor VARCHAR(255),
    wireless_charging VARCHAR(255),
    camera_sensor VARCHAR(255),
    camera_settings VARCHAR(255),
    image_resolution VARCHAR(255),
    shooting_modes VARCHAR(255),
    camera_features VARCHAR(255),
    video_recording VARCHAR(255),
    camera_setup VARCHAR(255),
    resolution VARCHAR(255),
    autofocus VARCHAR(255),
    colours VARCHAR(255),
    thickness VARCHAR(255),
    build_material VARCHAR(255),
    ruggedness VARCHAR(255),
    waterproof VARCHAR(255),
    weight VARCHAR(255),
    height VARCHAR(255),
    width VARCHAR(255),
    display_type VARCHAR(255),
    bezelless_display VARCHAR(255),
    hdr_support VARCHAR(255),
    touch_screen VARCHAR(255),
    pixel_density VARCHAR(255),
    brightness VARCHAR(255),
    screen_size VARCHAR(255),
    refresh_rate VARCHAR(255),
    aspect_ratio VARCHAR(255),
    screen_to_body_ratio VARCHAR(255),
    screen_protection VARCHAR(255),
    launch_date VARCHAR(255),
    operating_system VARCHAR(255),
    brand VARCHAR(255),
    stereo_speakers VARCHAR(255),
    audio_features VARCHAR(255),
    audio_jack VARCHAR(255),
    loudspeaker VARCHAR(255),
    wifi_calling VARCHAR(255),
    sim_slots VARCHAR(255),
    network_support VARCHAR(255),
    bluetooth VARCHAR(255),
    wifi VARCHAR(255),
    usb_connectivity VARCHAR(255),
    wifi_features VARCHAR(255),
    volte VARCHAR(255),
    gps VARCHAR(255),
    sim_size VARCHAR(255),
    ram VARCHAR(255),
    cpu VARCHAR(255),
    fabrication VARCHAR(255),
    chipset VARCHAR(255),
    ram_type VARCHAR(255),
    graphics VARCHAR(255),
    architecture VARCHAR(255),
    fingerprint_sensor VARCHAR(255),
    internal_memory VARCHAR(255),
    expandable_memory VARCHAR(255)
);
SELECT * FROM mobiles;

CREATE TABLE tablets (
    id INT AUTO_INCREMENT PRIMARY KEY,
    image_url VARCHAR(255),
	score VARCHAR(255),
    price varchar(255),
    tablet_name VARCHAR(255),
    brand VARCHAR(255),
    model VARCHAR(255),
    operating_system VARCHAR(255),
    custom_ui VARCHAR(255),
    launch_date VARCHAR(255),
    
    battery_type VARCHAR(255),
    user_replaceable_battery VARCHAR(255),
    quick_charging VARCHAR(255),
    usb_type_c VARCHAR(255),
    battery_capacity VARCHAR(255),
    
    camera_settings VARCHAR(255),
    camera_features VARCHAR(255),
    video_recording VARCHAR(255),
    shooting_modes VARCHAR(255),
    camera_resolution VARCHAR(255),
    autofocus VARCHAR(255),
    flash VARCHAR(255),
    image_resolution VARCHAR(255),
    
    width VARCHAR(255),
    weight VARCHAR(255),
    height VARCHAR(255),
    thickness VARCHAR(255),
    colors VARCHAR(255),
    
    screen_protection VARCHAR(255),
    screen_size VARCHAR(255),
    display_type VARCHAR(255),
    touch_screen VARCHAR(255),
    pixel_density VARCHAR(255),
    screen_to_body_ratio VARCHAR(255),
    screen_resolution VARCHAR(255),
    
    fm_radio VARCHAR(255),
    audio_features VARCHAR(255),
    audio_jack VARCHAR(255),
    
    expandable_memory VARCHAR(255),
    internal_memory VARCHAR(255),
    
    network_support VARCHAR(255),
    usb_connectivity VARCHAR(255),
    wifi VARCHAR(255),
    voice_calling VARCHAR(255),
    volte VARCHAR(255),
    bluetooth VARCHAR(255),
    nfc VARCHAR(255),
    wifi_features VARCHAR(255),
    
    architecture VARCHAR(255),
    processor VARCHAR(255),
    graphics VARCHAR(255),
    ram VARCHAR(255),
    chipset VARCHAR(255),
    
    smart_tv_camera VARCHAR(255),
    
    other_sensors VARCHAR(255),
    fingerprint_sensor VARCHAR(255)
    
    -- Add more columns here if needed
);

SELECT * FROM tablets;


